// AUTO-GENERATED FILE, THEN HAND-EDITED.
// Generated by the Ballerina OpenAPI tool from specs/design/components/library-service/openapi.yaml,
// with resource bodies filled in and the response records tightened.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Search the catalogue by genre and/or author
    #
    # + genre - Filter to books of this genre
    # + author - Filter to books by this author
    # + return - returns can be any of following types
    # BooksPage (Matching books)
    # ErrorBadRequest (Invalid filter parameter)
    resource function get books(http:Request req, string? genre, string? author, int 'limit = 20, int offset = 0) returns BooksPage|ErrorBadRequest {
        map<string[]> queryParams = req.getQueryParams();
        foreach string paramName in queryParams.keys() {
            if paramName != "genre" && paramName != "author" && paramName != "limit" && paramName != "offset" {
                Error errorBody = {code: 400, message: "Invalid query parameter", description: "Unsupported query parameter: " + paramName};
                return <ErrorBadRequest>{body: errorBody};
            }
        }

        int effectiveLimit = 'limit;
        if effectiveLimit > MAX_LIMIT {
            effectiveLimit = MAX_LIMIT;
        }
        if effectiveLimit < 0 {
            effectiveLimit = DEFAULT_LIMIT;
        }
        int effectiveOffset = offset;
        if effectiveOffset < 0 {
            effectiveOffset = 0;
        }

        string? genreFilter = genre is string ? genre.toLowerAscii() : ();
        string? authorFilter = author is string ? author.toLowerAscii() : ();

        Book[] filtered = from Book b in seedBooks
            where (genreFilter is () || b.genre.toLowerAscii() == genreFilter)
            where (authorFilter is () || b.author.toLowerAscii() == authorFilter)
            select b;

        int total = filtered.length();
        int endIndex = effectiveOffset + effectiveLimit;
        if endIndex > total {
            endIndex = total;
        }

        Book[] pageData = [];
        if effectiveOffset < total {
            pageData = filtered.slice(effectiveOffset, endIndex);
        }

        string? next = ();
        if endIndex < total {
            next = buildPageUri(genre, author, effectiveLimit, endIndex);
        }

        string? previous = ();
        if effectiveOffset > 0 {
            int prevOffset = effectiveOffset - effectiveLimit;
            if prevOffset < 0 {
                prevOffset = 0;
            }
            previous = buildPageUri(genre, author, effectiveLimit, prevOffset);
        }

        BooksPage page = {count: total, next: next, previous: previous, data: pageData};
        return page;
    }

    # Get one book's details and availability
    #
    # + return - returns can be any of following types
    # Book (The book)
    # ErrorNotFound (No book with this id)
    resource function get books/[string id]() returns Book|ErrorNotFound {
        foreach Book candidate in seedBooks {
            if candidate.id == id {
                return candidate;
            }
        }
        Error errorBody = {code: 404, message: "Book not found", description: "No book with id '" + id + "'"};
        return <ErrorNotFound>{body: errorBody};
    }
}

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type Book record {|
    string id;
    string title;
    string author;
    string genre;
    int year;
    boolean available;
|};

public type BooksPage record {|
    # total matching items
    int count;
    # relative URI of the next page
    string? next;
    # relative URI of the previous page
    string? previous;
    Book[] data;
|};

public type Error record {|
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
|};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};
